name: beer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  retrofit: ^4.0.1
  json_annotation: ^4.8.0
  freezed:
  freezed_annotation: any
  dio: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^6.3.1
  retrofit_generator: any

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true